BIN_SELECTION: all
BLUR_SIGMA: 0
COMBINED_MATRICES_DIR: /scratch_lg/image-content/ameyasd//best_mp_all_v2/custom/20min/new_labels/mp/all/
COMBINED_MATRICES_FILE_BASENAME: /scratch_lg/image-content/ameyasd//best_mp_all_v2/custom/20min/new_labels/mp/all/combined_matrices_%s.npz
COMMANDS_FILE: /scratch_lg/image-content/ameyasd/europa-onboard-science/src/caps_els/secondary_scripts/trainset_v2_best_mp
CREATION_COMMAND: ./create_config.py best_mp_all_v2.yaml --results best_mp_all_v2
  --commands trainset_v2_best_mp --lbls new_labels/mp/all/ --custom --mode test-v2
CROSSINGS_DIR: /scratch_lg/image-content/ameyasd/crossings_updated/
CUSTOM: true
DATA_DIR: /scratch_lg/image-content/ameyasd/crossings_updated/data/
ERROR_ANALYSIS_DIR: /scratch_lg/image-content/ameyasd//best_mp_all_v2/custom/error_analysis/new_labels/mp/all/
FILTER: no_filter
FILTER_SIZE: 1
LABELS_DIR: /scratch_lg/image-content/ameyasd/crossings_updated/new_labels/mp/all/
LABELS_SUBDIR: new_labels/mp/all/
MINIMUM_JOB_ARRAY_SIZE: 138
MODE: test-v2
NUM_ALGORITHMS: 6
NUM_DATAFILES: 23
PCA_COMPONENTS_DIR: /scratch_lg/image-content/ameyasd//best_mp_all_v2/custom/pca_components/
RANDOM_PLOTS_DIR: /scratch_lg/image-content/ameyasd//best_mp_all_v2/custom/random_plots/new_labels/mp/all/
RESULTS_DIR: /scratch_lg/image-content/ameyasd//best_mp_all_v2/custom/
SCRIPTS_DIR: /scratch_lg/image-content/ameyasd/europa-onboard-science/src/caps_els/
THRESHOLDS_DIR: /scratch_lg/image-content/ameyasd//best_mp_all_v2/custom/thresholds/new_labels/mp/all/
TIME_TOLERANCE: 20
TRANSFORM: anscombe_transform
