BLUR_SIGMA: 2
COMBINED_MATRICES_DIR: /scratch_lg/image-content/ameyasd//crossings_test_results/anscombe_transform/blur_2/ignore_unpaired/20min/new_labels/mp/all/
COMBINED_MATRICES_FILE_BASENAME: /scratch_lg/image-content/ameyasd//crossings_test_results/anscombe_transform/blur_2/ignore_unpaired/20min/new_labels/mp/all/combined_matrices_%s.npz
COMMANDS_FILE: /scratch_lg/image-content/ameyasd/europa-onboard-science/src/caps_els/secondary_scripts/commands/parameter_sweep_commands_testset_blur2_mp_all
CREATION_COMMAND: ./create_config.py --mode test --results crossings_test_results
  --transform anscombe_transform --ignore_unpaired --commands commands/parameter_sweep_commands_testset_blur2_mp_all
  -b 2 --lbls new_labels/mp/all/ blur_2_testset_mp_all.yaml
CROSSINGS_DIR: /scratch_lg/image-content/ameyasd/crossings_updated/
DATA_DIR: /scratch_lg/image-content/ameyasd/crossings_updated/data/
IGNORE_UNPAIRED: true
LABELS_DIR: /scratch_lg/image-content/ameyasd/crossings_updated/new_labels/mp/all/
LABELS_SUBDIR: new_labels/mp/all/
MINIMUM_JOB_ARRAY_SIZE: 3308
MODE: test
NUM_ALGORITHMS: 4
NUM_DATAFILES: 827
PCA_COMPONENTS_DIR: /scratch_lg/image-content/ameyasd//crossings_test_results/anscombe_transform/blur_2/ignore_unpaired/pca_components/
RANDOM_PLOTS_DIR: /scratch_lg/image-content/ameyasd//crossings_test_results/anscombe_transform/blur_2/ignore_unpaired/random_plots/new_labels/mp/all/
RESULTS_DIR: /scratch_lg/image-content/ameyasd//crossings_test_results/anscombe_transform/blur_2/ignore_unpaired/
SCRIPTS_DIR: /scratch_lg/image-content/ameyasd/europa-onboard-science/src/caps_els/
THRESHOLDS_DIR: /scratch_lg/image-content/ameyasd//crossings_test_results/anscombe_transform/blur_2/ignore_unpaired/thresholds/new_labels/mp/all/
TIME_TOLERANCE: 20
TRANSFORM: anscombe_transform
