BLUR_SIGMA: 5
COMBINED_MATRICES_DIR: /scratch_lg/image-content/ameyasd//crossings_test_results/anscombe_transform/blur_5/ignore_unpaired/20min/new_labels/bs/out/
COMBINED_MATRICES_FILE_BASENAME: /scratch_lg/image-content/ameyasd//crossings_test_results/anscombe_transform/blur_5/ignore_unpaired/20min/new_labels/bs/out/combined_matrices_%s.npz
COMMANDS_FILE: /scratch_lg/image-content/ameyasd/europa-onboard-science/src/caps_els/secondary_scripts/parameter_sweep_commands_testset_blur5
CREATION_COMMAND: ./create_config.py --mode test --results crossings_test_results
  --transform anscombe_transform --ignore_unpaired --commands parameter_sweep_commands_testset_blur5
  -b 5 --lbls new_labels/bs/out/ blur_5_testset_bs_out.yaml
DATA_DIR: /scratch_lg/image-content/ameyasd/crossings_updated/data/
BIN_SELECTION: ignore_unpaired
FILTER: no_filter
FILTER_SIZE: 1
LABELS_DIR: /scratch_lg/image-content/ameyasd/crossings_updated/new_labels/bs/out/
LABELS_SUBDIR: new_labels/bs/out/
MINIMUM_JOB_ARRAY_SIZE: 6120
MODE: test
NUM_ALGORITHMS: 5
NUM_DATAFILES: 1224
PCA_COMPONENTS_DIR: /scratch_lg/image-content/ameyasd//crossings_test_results/anscombe_transform/blur_5/ignore_unpaired/pca_components/
RESULTS_DIR: /scratch_lg/image-content/ameyasd//crossings_test_results/anscombe_transform/blur_5/ignore_unpaired/
SCRIPTS_DIR: /scratch_lg/image-content/ameyasd/europa-onboard-science/src/caps_els/
THRESHOLDS_DIR: /scratch_lg/image-content/ameyasd//crossings_test_results/anscombe_transform/blur_5/ignore_unpaired/thresholds/
TIME_TOLERANCE: 20
TRANSFORM: anscombe_transform
