COMBINED_RESULTS_DIR: /scratch_lg/image-content/ameyasd/crossings_test_results/anscombe_transform/20min/new_labels/bs/out/
COMBINED_RESULTS_FILE: /scratch_lg/image-content/ameyasd/crossings_test_results/anscombe_transform/20min/new_labels/bs/out/combined_results_.npz
COMMANDS_FILE: /scratch_lg/image-content/ameyasd/europa-onboard-science/src/caps_els/secondary_scripts/parameter_sweep_commands_testset
DATA_DIR: /scratch_lg/image-content/ameyasd/crossings_updated/data/
LABELS_DIR: /scratch_lg/image-content/ameyasd/crossings_updated/new_labels/bs/out/
LABELS_SUBDIR: new_labels/bs/out/
MODE: test
PCA_COMPONENTS_DIR: /scratch_lg/image-content/ameyasd/crossings_test_results/anscombe_transform/pca_components/
QUERY_FOR_COMBINE: ''
RESULTS_DIR: /scratch_lg/image-content/ameyasd/crossings_test_results/anscombe_transform/
SCRIPTS_DIR: /scratch_lg/image-content/ameyasd/europa-onboard-science/src/caps_els/
THRESHOLDS_DIR: /scratch_lg/image-content/ameyasd/crossings_test_results/anscombe_transform/thresholds/
TIME_TOLERANCE: 20
TRANSFORM: anscombe_transform
