BIN_SELECTION: center
BLUR_SIGMA: 5
COMBINED_MATRICES_DIR: /scratch_lg/image-content/ameyasd//crossings_test_results/anscombe_transform/blur_5/center/median_filter_120/20min/new_labels/bs/all/
COMBINED_MATRICES_FILE_BASENAME: /scratch_lg/image-content/ameyasd//crossings_test_results/anscombe_transform/blur_5/center/median_filter_120/20min/new_labels/bs/all/combined_matrices_%s.npz
COMMANDS_FILE: /scratch_lg/image-content/ameyasd/europa-onboard-science/src/caps_els/secondary_scripts/commands/parameter_sweep_commands_testset_blur5_bs_all_medfilter_center
CREATION_COMMAND: ./create_config.py --mode test --results crossings_test_results
  --transform anscombe_transform --bin_selection center --commands commands/parameter_sweep_commands_testset_blur5_bs_all_medfilter_center
  -b 5 --lbls new_labels/bs/all/ -f median_filter -fsize 120 testset_bs_all_med_center.yaml
CROSSINGS_DIR: /scratch_lg/image-content/ameyasd/crossings_updated/
DATA_DIR: /scratch_lg/image-content/ameyasd/crossings_updated/data/
ERROR_ANALYSIS_DIR: /scratch_lg/image-content/ameyasd//crossings_test_results/anscombe_transform/blur_5/center/median_filter_120/error_analysis/new_labels/bs/all/
FILTER: median_filter
FILTER_SIZE: 120
LABELS_DIR: /scratch_lg/image-content/ameyasd/crossings_updated/new_labels/bs/all/
LABELS_SUBDIR: new_labels/bs/all/
MINIMUM_JOB_ARRAY_SIZE: 2208
MODE: test
NUM_ALGORITHMS: 6
NUM_DATAFILES: 368
PCA_COMPONENTS_DIR: /scratch_lg/image-content/ameyasd//crossings_test_results/anscombe_transform/blur_5/center/median_filter_120/pca_components/
RANDOM_PLOTS_DIR: /scratch_lg/image-content/ameyasd//crossings_test_results/anscombe_transform/blur_5/center/median_filter_120/random_plots/new_labels/bs/all/
RESULTS_DIR: /scratch_lg/image-content/ameyasd//crossings_test_results/anscombe_transform/blur_5/center/median_filter_120/
SCRIPTS_DIR: /scratch_lg/image-content/ameyasd/europa-onboard-science/src/caps_els/
THRESHOLDS_DIR: /scratch_lg/image-content/ameyasd//crossings_test_results/anscombe_transform/blur_5/center/median_filter_120/thresholds/new_labels/bs/all/
TIME_TOLERANCE: 20
TRANSFORM: anscombe_transform
