BIN_SELECTION: ignore_unpaired
BLUR_SIGMA: 0
COMBINED_MATRICES_DIR: /scratch_lg/image-content/ameyasd//crossings_new_partition/train-v2/anscombe_transform/blur_0/ignore_unpaired/max_filter_120/20min/new_labels/mp/all/
COMBINED_MATRICES_FILE_BASENAME: /scratch_lg/image-content/ameyasd//crossings_new_partition/train-v2/anscombe_transform/blur_0/ignore_unpaired/max_filter_120/20min/new_labels/mp/all/combined_matrices_%s.npz
COMMANDS_FILE: /scratch_lg/image-content/ameyasd/europa-onboard-science/src/caps_els/secondary_scripts/commands/parameter_sweep_commands
CREATION_COMMAND: ./create_config.py --mode train-v2 --results crossings_new_partition
  --transform anscombe_transform --bin_selection ignore_unpaired --commands commands/parameter_sweep_commands
  -b 0 --lbls new_labels/mp/all/ -f max_filter -fsize 120 trainset_v2_mp_all_max_b0.yaml
CROSSINGS_DIR: /scratch_lg/image-content/ameyasd/crossings_updated/
CUSTOM: false
DATA_DIR: /scratch_lg/image-content/ameyasd/crossings_updated/data/
ERROR_ANALYSIS_DIR: /scratch_lg/image-content/ameyasd//crossings_new_partition/train-v2/anscombe_transform/blur_0/ignore_unpaired/max_filter_120/error_analysis/new_labels/mp/all/
FILTER: max_filter
FILTER_SIZE: 120
LABELS_DIR: /scratch_lg/image-content/ameyasd/crossings_updated/new_labels/mp/all/
LABELS_SUBDIR: new_labels/mp/all/
MINIMUM_JOB_ARRAY_SIZE: 7104
MODE: train-v2
NUM_ALGORITHMS: 111
NUM_DATAFILES: 64
PCA_COMPONENTS_DIR: /scratch_lg/image-content/ameyasd//crossings_new_partition/train-v2/anscombe_transform/blur_0/ignore_unpaired/max_filter_120/pca_components/
RANDOM_PLOTS_DIR: /scratch_lg/image-content/ameyasd//crossings_new_partition/train-v2/anscombe_transform/blur_0/ignore_unpaired/max_filter_120/random_plots/new_labels/mp/all/
RESULTS_DIR: /scratch_lg/image-content/ameyasd//crossings_new_partition/train-v2/anscombe_transform/blur_0/ignore_unpaired/max_filter_120/
SCRIPTS_DIR: /scratch_lg/image-content/ameyasd/europa-onboard-science/src/caps_els/
THRESHOLDS_DIR: /scratch_lg/image-content/ameyasd//crossings_new_partition/train-v2/anscombe_transform/blur_0/ignore_unpaired/max_filter_120/thresholds/new_labels/mp/all/
TIME_TOLERANCE: 20
TRANSFORM: anscombe_transform
